# Configuration for GitHub Actions Labeler
# This file defines rules for automatically labeling pull requests based on changed files

# Documentation and README changes
documentation:
  - changed-files:
    - any-glob-to-any-file: ['README.md', 'CHANGELOG.md', 'CONTRIBUTING.md', 'LICENSE*']
    - any-glob-to-any-file: ['docs/**/*', '*.md']

# Frontend/UI changes (Vaadin views and components)
frontend:
  - changed-files:
    - any-glob-to-any-file: ['src/main/java/**/ui/**/*', 'src/main/java/**/view/**/*']
    - any-glob-to-any-file: ['src/main/resources/META-INF/resources/**/*']
    - any-glob-to-any-file: ['frontend/**/*']

# Backend/API changes
backend:
  - changed-files:
    - any-glob-to-any-file: ['src/main/java/**/service/**/*', 'src/main/java/**/controller/**/*']
    - any-glob-to-any-file: ['src/main/java/**/repository/**/*', 'src/main/java/**/domain/**/*']

# Database related changes
database:
  - changed-files:
    - any-glob-to-any-file: ['src/main/resources/db/**/*', 'src/main/resources/**/migration/**/*']
    - any-glob-to-any-file: ['src/main/java/**/entity/**/*', 'src/main/java/**/domain/**/*']
    - any-glob-to-any-file: ['**/*flyway*', '**/*liquibase*']

# Configuration changes
configuration:
  - changed-files:
    - any-glob-to-any-file: ['src/main/resources/*.yml', 'src/main/resources/*.yaml']
    - any-glob-to-any-file: ['src/main/resources/*.properties', 'src/main/resources/application*']
    - any-glob-to-any-file: ['pom.xml', 'mvnw*', '.mvn/**/*']

# Test changes
tests:
  - changed-files:
    - any-glob-to-any-file: ['src/test/**/*', '**/test/**/*']
    - any-glob-to-any-file: ['**/*Test.java', '**/*Tests.java', '**/*IT.java']

# GitHub Actions and CI/CD
ci-cd:
  - changed-files:
    - any-glob-to-any-file: ['.github/**/*']
    - any-glob-to-any-file: ['**/*Dockerfile*', 'docker-compose*', '.dockerignore']

# Security related changes
security:
  - changed-files:
    - any-glob-to-any-file: ['owasp-dependency-check-suppressions.xml']
    - any-glob-to-any-file: ['.github/workflows/security-scan.yml', '.github/workflows/dependency-review.yml']
    - any-glob-to-any-file: ['**/*security*', '**/*auth*']

# Wrestling/Game domain specific
wrestling:
  - changed-files:
    - any-glob-to-any-file: ['src/main/java/**/wrestler/**/*', 'src/main/java/**/match/**/*']
    - any-glob-to-any-file: ['src/main/java/**/show/**/*', 'src/main/java/**/championship/**/*']
    - any-glob-to-any-file: ['src/main/resources/wrestlers.json', 'src/main/resources/championships.json']

# AI/Narration features
ai:
  - changed-files:
    - any-glob-to-any-file: ['src/main/java/**/ai/**/*', 'src/main/java/**/narration/**/*']
    - any-glob-to-any-file: ['src/main/resources/*ai*', 'src/main/resources/application-ai*']

# Dependencies and build
dependencies:
  - changed-files:
    - any-glob-to-any-file: ['pom.xml']
    - any-glob-to-any-file: ['package*.json', 'yarn.lock', 'package-lock.json']

# Scripts and utilities
scripts:
  - changed-files:
    - any-glob-to-any-file: ['scripts/**/*', '*.sh', '*.bat']

# Major changes (multiple areas affected)
major:
  - changed-files:
    - any-glob-to-any-file: ['src/main/java/**/*']
    - all-globs-to-all-files: ['src/main/java/**/ui/**/*', 'src/main/java/**/service/**/*', 'src/main/java/**/domain/**/*']
