/*
* Copyright (C) 2026 Software Consulting Dreams LLC
*
* This program is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with this program.  If not, see <www.gnu.org>.
*/
package com.github.javydreamercsw;

import static org.junit.jupiter.api.Assertions.fail;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.HexFormat;
import java.util.List;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;

/**
 * Guards against modification of released Flyway migration scripts.
 *
 * <p>Scripts at or below the version recorded in {@code .released} are frozen: changing them after
 * deployment causes Flyway checksum validation failures in production (as happened during the 2.X.X
 * upgrade). This test fails immediately on {@code mvn test} if any such file is edited, with no
 * database or Docker required.
 *
 * <p>The {@code .checksums} manifest is generated by {@code
 * scripts/generate-migration-checksums.sh} and must be committed whenever {@code .released} is
 * updated (i.e. at each release).
 */
class ReleasedMigrationChecksumTest {

  @ParameterizedTest(name = "{0}")
  @ValueSource(strings = {"h2", "mysql"})
  void released_migration_scripts_must_not_be_modified(String dbType) throws Exception {
    Path migrationDir = Paths.get("src/main/resources/db/migration", dbType);
    Path releasedFile = migrationDir.resolve(".released");
    Path checksumsFile = migrationDir.resolve(".checksums");

    assertFileExists(releasedFile, "Run scripts/generate-migration-checksums.sh to create it.");
    assertFileExists(
        checksumsFile,
        "Run scripts/generate-migration-checksums.sh to create it."
            + " This file must be committed alongside .released.");

    List<String> violations = new ArrayList<>();

    for (String line : Files.readAllLines(checksumsFile)) {
      line = line.trim();
      if (line.isEmpty()) continue;

      String[] parts = line.split("  ", 2);
      if (parts.length != 2) {
        violations.add("Malformed line in .checksums: " + line);
        continue;
      }

      String expectedHash = parts[0];
      String filename = parts[1];
      Path scriptPath = migrationDir.resolve(filename);

      if (!Files.exists(scriptPath)) {
        violations.add(
            filename
                + ": file missing — released migration scripts must not be deleted."
                + " Add a new migration to undo the change instead.");
        continue;
      }

      String actualHash = sha256hex(scriptPath);
      if (!expectedHash.equalsIgnoreCase(actualHash)) {
        violations.add(
            filename
                + ": checksum mismatch."
                + "\n    expected: "
                + expectedHash
                + "\n    actual:   "
                + actualHash
                + "\n    Released migration scripts must not be edited after deployment."
                + " Create a new migration script to make corrections instead.");
      }
    }

    if (!violations.isEmpty()) {
      fail(
          "["
              + dbType
              + "] Released migration scripts have been modified ("
              + violations.size()
              + " violation(s)):\n\n"
              + String.join("\n\n", violations)
              + "\n\nTo fix: revert the changes to the listed scripts and add a new migration"
              + " (with the next available version number) for any schema corrections.");
    }
  }

  private static void assertFileExists(Path path, String hint) {
    if (!Files.exists(path)) {
      fail("Required file not found: " + path + "\n" + hint);
    }
  }

  private static String sha256hex(Path file) throws IOException, NoSuchAlgorithmException {
    MessageDigest digest = MessageDigest.getInstance("SHA-256");
    digest.update(Files.readAllBytes(file));
    return HexFormat.of().formatHex(digest.digest());
  }
}
