CREATE TABLE wrestler_state_history
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wrestler_id BIGINT       NOT NULL,
    universe_id BIGINT       NOT NULL,
    recorded_at TIMESTAMP    NOT NULL,
    fans        BIGINT       NOT NULL DEFAULT 0,
    tier        VARCHAR(50)  NOT NULL,
    CONSTRAINT fk_wsh_wrestler FOREIGN KEY (wrestler_id) REFERENCES wrestler (wrestler_id),
    CONSTRAINT fk_wsh_universe FOREIGN KEY (universe_id) REFERENCES universe (id)
);

CREATE INDEX idx_wsh_lookup ON wrestler_state_history (wrestler_id, universe_id, recorded_at);
