CREATE TABLE tournament (
    tournament_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    format_id VARCHAR(64) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'SCHEDULED',
    universe_id BIGINT,
    title_id BIGINT,
    start_date DATE,
    end_date DATE,
    CONSTRAINT fk_tournament_universe FOREIGN KEY (universe_id) REFERENCES universe(id),
    CONSTRAINT fk_tournament_title FOREIGN KEY (title_id) REFERENCES title(title_id)
);

CREATE TABLE tournament_entry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tournament_id BIGINT NOT NULL,
    wrestler_id BIGINT NOT NULL,
    seed INT NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    CONSTRAINT fk_entry_tournament FOREIGN KEY (tournament_id) REFERENCES tournament(tournament_id),
    CONSTRAINT fk_entry_wrestler FOREIGN KEY (wrestler_id) REFERENCES wrestler(wrestler_id)
);

CREATE TABLE tournament_round (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tournament_id BIGINT NOT NULL,
    round_number INT NOT NULL,
    round_name VARCHAR(64) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    show_id BIGINT,
    CONSTRAINT fk_round_tournament FOREIGN KEY (tournament_id) REFERENCES tournament(tournament_id),
    CONSTRAINT fk_round_show FOREIGN KEY (show_id) REFERENCES wrestling_show(show_id)
);

CREATE TABLE tournament_match (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    round_id BIGINT NOT NULL,
    entrant1_id BIGINT NOT NULL,
    entrant2_id BIGINT NOT NULL,
    segment_id BIGINT,
    winner_entry_id BIGINT,
    CONSTRAINT fk_match_round FOREIGN KEY (round_id) REFERENCES tournament_round(id),
    CONSTRAINT fk_match_entrant1 FOREIGN KEY (entrant1_id) REFERENCES tournament_entry(id),
    CONSTRAINT fk_match_entrant2 FOREIGN KEY (entrant2_id) REFERENCES tournament_entry(id),
    CONSTRAINT fk_match_segment FOREIGN KEY (segment_id) REFERENCES segment(segment_id),
    CONSTRAINT fk_match_winner FOREIGN KEY (winner_entry_id) REFERENCES tournament_entry(id),
    CONSTRAINT uq_match_segment UNIQUE (segment_id)
);
