ALTER TABLE wrestler ADD COLUMN last_sync TIMESTAMP WITH TIME ZONE;
ALTER TABLE show ADD COLUMN last_sync TIMESTAMP WITH TIME ZONE;
ALTER TABLE title ADD COLUMN last_sync TIMESTAMP WITH TIME ZONE;
ALTER TABLE faction ADD COLUMN last_sync TIMESTAMP WITH TIME ZONE;
ALTER TABLE team ADD COLUMN last_sync TIMESTAMP WITH TIME ZONE;
ALTER TABLE injury ADD COLUMN last_sync TIMESTAMP WITH TIME ZONE;
ALTER TABLE segment ADD COLUMN last_sync TIMESTAMP WITH TIME ZONE;
