ALTER TABLE segment_rule ADD COLUMN external_id VARCHAR(255);
ALTER TABLE segment_rule ADD COLUMN last_sync TIMESTAMP WITH TIME ZONE;
ALTER TABLE show_type ADD COLUMN external_id VARCHAR(255);
ALTER TABLE show_type ADD COLUMN last_sync TIMESTAMP WITH TIME ZONE;
ALTER TABLE card_set ADD COLUMN external_id VARCHAR(255);
ALTER TABLE card_set ADD COLUMN last_sync TIMESTAMP WITH TIME ZONE;
ALTER TABLE segment_type ADD COLUMN external_id VARCHAR(255);
ALTER TABLE segment_type ADD COLUMN last_sync TIMESTAMP WITH TIME ZONE;
ALTER TABLE card ADD COLUMN external_id VARCHAR(255);
ALTER TABLE card ADD COLUMN last_sync TIMESTAMP WITH TIME ZONE;
ALTER TABLE deck ADD COLUMN external_id VARCHAR(255);
ALTER TABLE deck ADD COLUMN last_sync TIMESTAMP WITH TIME ZONE;
ALTER TABLE deck_card ADD COLUMN external_id VARCHAR(255);
ALTER TABLE deck_card ADD COLUMN last_sync TIMESTAMP WITH TIME ZONE;
ALTER TABLE rivalry ADD COLUMN external_id VARCHAR(255);
ALTER TABLE rivalry ADD COLUMN last_sync TIMESTAMP WITH TIME ZONE;


