-- ATW-0331 phase 2: PLE template assignments for segment types and rules.
-- Each row targets exactly one of segment_type_id / segment_rule_id and carries
-- its own mode: ENCOURAGED (AI preference) or AUTO_ATTACH (deterministic merge
-- at proposal approval).
CREATE TABLE IF NOT EXISTS show_template_segment_assignment (
  assignment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  template_id BIGINT NOT NULL,
  segment_type_id BIGINT,
  segment_rule_id BIGINT,
  mode VARCHAR(20) NOT NULL,
  creation_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_sta_template FOREIGN KEY (template_id) REFERENCES show_template (template_id),
  CONSTRAINT fk_sta_segment_type FOREIGN KEY (segment_type_id) REFERENCES segment_type (segment_type_id),
  CONSTRAINT fk_sta_segment_rule FOREIGN KEY (segment_rule_id) REFERENCES segment_rule (segment_rule_id)
);
