-- ATW-oloa: generic multi-entrant tournament matches (N qualifiers -> M final).
-- entrant1_id/entrant2_id stay NOT NULL and keep meaning "the classic two sides" for
-- singles matches; when a match has 3+ entrants (Free-for-All qualifiers, multi-man
-- finals), the ordered participant rows below are the authoritative entrant list and
-- entrant1/entrant2 mirror the first two slots for backward compatibility.

CREATE TABLE tournament_match_participant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id BIGINT NOT NULL,
    entry_id BIGINT NOT NULL,
    slot INT NOT NULL,
    CONSTRAINT fk_tmp_match FOREIGN KEY (match_id) REFERENCES tournament_match(id) ON DELETE CASCADE,
    CONSTRAINT fk_tmp_entry FOREIGN KEY (entry_id) REFERENCES tournament_entry(id),
    CONSTRAINT uq_tmp_match_slot UNIQUE (match_id, slot),
    CONSTRAINT uq_tmp_match_entry UNIQUE (match_id, entry_id)
);

CREATE INDEX idx_tmp_match ON tournament_match_participant(match_id);
