-- Money in the Bank-style briefcase (ATW-8p72): a held, cashable prize awarded to the
-- winner of a briefcase-deciding tournament (e.g. "Time Vault"). NOT a title — no reigns,
-- defenses, contenders or rankings. The holder may cash it in exactly once, at any time,
-- for a title match against the reigning champion(s) of any active championship.
-- status: HELD → CASHED_IN | EXPIRED | VOIDED
CREATE TABLE title_opportunity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    status VARCHAR(16) NOT NULL,
    wrestler_id BIGINT NOT NULL REFERENCES wrestler(wrestler_id),
    universe_id BIGINT NULL REFERENCES universe(id),
    earned_at DATE NOT NULL,
    earned_from_tournament_id BIGINT NULL REFERENCES tournament(tournament_id),
    expiry_date DATE NULL,
    cashed_at DATE NULL,
    cashed_at_segment_id BIGINT NULL REFERENCES segment(segment_id),
    cashed_against_title_id BIGINT NULL REFERENCES title(title_id)
);

CREATE INDEX idx_opp_wrestler ON title_opportunity(wrestler_id);
CREATE INDEX idx_opp_tournament ON title_opportunity(earned_from_tournament_id);
CREATE INDEX idx_opp_status ON title_opportunity(status);

-- Briefcase-deciding tournament payoff (ATW-8p72): the winner earns a cashable
-- TitleOpportunity instead of a title or a contender slot. Briefcase tournaments never
-- link a title — the winner may cash in against any reigning champion.
ALTER TABLE tournament ADD COLUMN briefcase_deciding BOOLEAN NOT NULL DEFAULT FALSE;
