ALTER TABLE wrestler ADD COLUMN drive INT DEFAULT 1 NOT NULL;
ALTER TABLE wrestler ADD COLUMN resilience INT DEFAULT 1 NOT NULL;
ALTER TABLE wrestler ADD COLUMN charisma INT DEFAULT 1 NOT NULL;
ALTER TABLE wrestler ADD COLUMN brawl INT DEFAULT 1 NOT NULL;
