CREATE TABLE ringside_action_type (
    ringside_action_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    increases_awareness BOOLEAN NOT NULL DEFAULT TRUE,
    can_cause_dq BOOLEAN NOT NULL DEFAULT TRUE,
    base_risk_multiplier DOUBLE PRECISION NOT NULL DEFAULT 1.0,
    external_id VARCHAR(255),
    last_sync TIMESTAMP,
    CONSTRAINT uk_ringside_action_type_name UNIQUE (name),
    CONSTRAINT uk_ringside_action_type_external_id UNIQUE (external_id)
);

CREATE TABLE ringside_action (
    ringside_action_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    description VARCHAR(1000),
    impact INT NOT NULL,
    risk INT NOT NULL,
    alignment VARCHAR(255) NOT NULL,
    ringside_action_type_id BIGINT NOT NULL,
    external_id VARCHAR(255),
    last_sync TIMESTAMP,
    CONSTRAINT fk_ringside_action_type FOREIGN KEY (ringside_action_type_id) REFERENCES ringside_action_type(ringside_action_type_id),
    CONSTRAINT uk_ringside_action_name UNIQUE (name),
    CONSTRAINT uk_ringside_action_external_id UNIQUE (external_id)
);
