ALTER TABLE faction ADD COLUMN alignment VARCHAR(50);
ALTER TABLE team ADD COLUMN theme_song VARCHAR(255);
ALTER TABLE team ADD COLUMN artist VARCHAR(255);
ALTER TABLE team ADD COLUMN team_finisher VARCHAR(255);
