-- Universe-Based State Isolation Migration (H2)

-- 1. Create universe table
CREATE TABLE IF NOT EXISTS universe (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(50) NOT NULL,
    creation_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. Create Default Universe
MERGE INTO universe (id, name, type) KEY (id) VALUES (1, 'Default Universe', 'GLOBAL');

-- 3. Create wrestler_state table
CREATE TABLE IF NOT EXISTS wrestler_state (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wrestler_id BIGINT NOT NULL,
    universe_id BIGINT NOT NULL,
    fans BIGINT DEFAULT 0,
    tier VARCHAR(255) NOT NULL,
    bumps INT DEFAULT 0,
    current_health INT,
    physical_condition INT DEFAULT 100,
    morale INT DEFAULT 100,
    management_stamina INT DEFAULT 100,
    faction_id BIGINT,
    manager_id BIGINT,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ws_wrestler FOREIGN KEY (wrestler_id) REFERENCES wrestler(wrestler_id),
    CONSTRAINT fk_ws_universe FOREIGN KEY (universe_id) REFERENCES universe(id),
    CONSTRAINT fk_ws_faction FOREIGN KEY (faction_id) REFERENCES faction(faction_id),
    CONSTRAINT fk_ws_manager FOREIGN KEY (manager_id) REFERENCES npc(id),
    CONSTRAINT uk_wrestler_universe UNIQUE (wrestler_id, universe_id)
);

-- 4. Scoping existing entities to Universe
ALTER TABLE injury ADD COLUMN IF NOT EXISTS universe_id BIGINT;

ALTER TABLE title ADD COLUMN IF NOT EXISTS universe_id BIGINT;

ALTER TABLE faction ADD COLUMN IF NOT EXISTS universe_id BIGINT;

ALTER TABLE team ADD COLUMN IF NOT EXISTS universe_id BIGINT;

ALTER TABLE drama_event ADD COLUMN IF NOT EXISTS universe_id BIGINT;

ALTER TABLE campaign ADD COLUMN IF NOT EXISTS universe_id BIGINT;

ALTER TABLE league ADD COLUMN IF NOT EXISTS universe_id BIGINT;

-- 5. Data Migration: Copy global state to the Default Universe (ID 1)
-- Only insert if the state doesn't already exist for that wrestler/universe combo
INSERT INTO wrestler_state 
(wrestler_id, universe_id, fans, tier, bumps, current_health, physical_condition, morale, management_stamina, faction_id, manager_id)
SELECT 
w.wrestler_id, 1, w.fans, w.tier, w.bumps, w.current_health, w.physical_condition, w.morale, w.management_stamina, w.faction_id, w.manager_id
FROM wrestler w
WHERE NOT EXISTS (
    SELECT 1 FROM wrestler_state ws 
    WHERE ws.wrestler_id = w.wrestler_id AND ws.universe_id = 1
);

-- Link existing records to the Default Universe
UPDATE injury SET universe_id = 1 WHERE universe_id IS NULL;
UPDATE title SET universe_id = 1 WHERE universe_id IS NULL;
UPDATE faction SET universe_id = 1 WHERE universe_id IS NULL;
UPDATE team SET universe_id = 1 WHERE universe_id IS NULL;
UPDATE drama_event SET universe_id = 1 WHERE universe_id IS NULL;
UPDATE campaign SET universe_id = 1 WHERE universe_id IS NULL;
UPDATE league SET universe_id = 1 WHERE universe_id IS NULL;
