-- Creates the universe table required by V77 (universe_members) and V81 (wrestler_state)
CREATE TABLE IF NOT EXISTS universe (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(50) NOT NULL,
    creation_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

MERGE INTO universe (id, name, type) KEY (id) VALUES (1, 'Default Universe', 'GLOBAL');
