-- Creates the wrestler_state table required by V79 (Deactivate_Same_Faction_Rivalries)
-- V81 (Decouple_Wrestler_State) uses CREATE TABLE IF NOT EXISTS so it will safely skip this
CREATE TABLE IF NOT EXISTS wrestler_state (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wrestler_id BIGINT NOT NULL,
    universe_id BIGINT NOT NULL,
    fans BIGINT DEFAULT 0,
    tier VARCHAR(255) NOT NULL,
    bumps INT DEFAULT 0,
    current_health INT,
    physical_condition INT DEFAULT 100,
    morale INT DEFAULT 100,
    management_stamina INT DEFAULT 100,
    faction_id BIGINT,
    manager_id BIGINT,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ws_wrestler FOREIGN KEY (wrestler_id) REFERENCES wrestler(wrestler_id),
    CONSTRAINT fk_ws_universe FOREIGN KEY (universe_id) REFERENCES universe(id),
    CONSTRAINT fk_ws_faction FOREIGN KEY (faction_id) REFERENCES faction(faction_id),
    CONSTRAINT fk_ws_manager FOREIGN KEY (manager_id) REFERENCES npc(id),
    CONSTRAINT uk_wrestler_universe UNIQUE (wrestler_id, universe_id)
);

-- Populate wrestler_state from existing wrestler data for the Default Universe
INSERT INTO wrestler_state
(wrestler_id, universe_id, fans, tier, bumps, current_health, physical_condition, morale, management_stamina, faction_id, manager_id)
SELECT
w.wrestler_id, 1, w.fans, w.tier, w.bumps, w.current_health, w.physical_condition, w.morale, w.management_stamina, w.faction_id, w.manager_id
FROM wrestler w
WHERE NOT EXISTS (SELECT 1 FROM wrestler_state ws WHERE ws.wrestler_id = w.wrestler_id AND ws.universe_id = 1);
