CREATE TABLE universe_expansion_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    universe_id BIGINT NOT NULL,
    expansion_code VARCHAR(255) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_universe_expansion UNIQUE (universe_id, expansion_code),
    CONSTRAINT fk_ues_universe FOREIGN KEY (universe_id) REFERENCES universe (id)
);

CREATE TABLE universe_wrestler_exclusions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    universe_id BIGINT NOT NULL,
    wrestler_id BIGINT NOT NULL,
    CONSTRAINT uk_universe_wrestler UNIQUE (universe_id, wrestler_id),
    CONSTRAINT fk_uwe_universe FOREIGN KEY (universe_id) REFERENCES universe (id),
    CONSTRAINT fk_uwe_wrestler FOREIGN KEY (wrestler_id) REFERENCES wrestler (wrestler_id)
);
