ALTER TABLE npc ADD COLUMN is_active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE segment_type ADD COLUMN is_active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE segment_rule ADD COLUMN is_active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE show_type ADD COLUMN is_active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE show_template ADD COLUMN is_active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE arena ADD COLUMN is_active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE location ADD COLUMN is_active BOOLEAN NOT NULL DEFAULT TRUE;
