ALTER TABLE card_set ADD COLUMN name VARCHAR(255);
UPDATE card_set SET name = set_code;
ALTER TABLE card_set ALTER COLUMN name SET NOT NULL;
ALTER TABLE card_set ADD CONSTRAINT UQ_CARD_SET_NAME UNIQUE (name);
ALTER TABLE card_set ADD CONSTRAINT UQ_CARD_SET_SET_CODE UNIQUE (set_code);
