CREATE TABLE inbox_item_target (
    inbox_item_target_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inbox_item_id BIGINT,
    target_id VARCHAR(255) NOT NULL,
    last_sync TIMESTAMP WITH TIME ZONE,
    external_id VARCHAR(255) UNIQUE,
    FOREIGN KEY (inbox_item_id) REFERENCES inbox_item(inbox_item_id)
);

INSERT INTO inbox_item_target (inbox_item_id, target_id, last_sync)
SELECT inbox_item_id, reference_id, NOW()
FROM inbox_item
WHERE reference_id IS NOT NULL;
